server:
  port: 8089

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/analytics_db
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: analytics-group