server:
  port: 8080

spring:
  cloud:
    gateway:
      # Global CORS (Allow Frontend Access)
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:3000"
              - "http://localhost:3001"
              - "http://localhost:3002"
              - "http://localhost:5173"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600

      # Routes
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: listing-service-vendor-me
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/listings/vendor/me
            - Method=GET
          filters:
            - name: CustomAuthFilter
        - id: listing-service-uploads
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/listings/uploads/**
          # No Auth Filter for static images
        - id: listing-service-upload
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/listings/upload
            - Method=POST
          filters:
            - name: CustomAuthFilter
        - id: listing-service-public-get
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/listings/**
            - Method=GET
          # Public GET access
        - id: listing-service
          uri: lb://LISTING-SERVICE
          predicates:
            - Path=/api/listings/**
          filters:
            - name: CustomAuthFilter
        - id: enquiry-service
          uri: lb://ENQUIRY-SERVICE
          predicates:
            - Path=/api/enquiries/**
          filters:
            - name: CustomAuthFilter
        - id: review-service
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
          filters:
            - name: CustomAuthFilter
        - id: financial-service
          uri: lb://FINANCIAL-SERVICE
          predicates:
            - Path=/api/financial/**
          filters:
            - name: CustomAuthFilter
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/api/search/**
        - id: calendar-service
          uri: lb://CALENDAR-SERVICE
          predicates:
            - Path=/api/calendar/**
          filters:
            - name: CustomAuthFilter
        - id: chat-service
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/chat/**
          filters:
            - name: CustomAuthFilter
        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/api/analytics/**
          filters:
            - name: CustomAuthFilter
        - id: notification-service
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/api/notify/**
          filters:
            - name: CustomAuthFilter

# JWT Secret for Gateway Validation
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970