server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enquiry_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      financialService:
        failureRateThreshold: 50