server:
  port: 8084

spring:
  application:
    name: enquiry-service
  datasource:
    url: jdbc:mysql://localhost:3307/enquiry_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      financialService:
        failureRateThreshold: 50