server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/financial_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
