server:
  port: 8085

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/notification_db

  # Mail Server (Update with real creds later)
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-app-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true