server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update

# Resilience4j for Listing Service calls
resilience4j:
  circuitbreaker:
    instances:
      listingService:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
