server:
  port: 8092

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/review_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update

# Resilience4j for Listing Service calls
resilience4j:
  circuitbreaker:
    instances:
      listingService:
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
