server:
  port: 8084

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/search_db
      auto-index-creation: true

  # Kafka Consumer Config
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: search-group-debug-fresh
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "com.wedding.listingService.dto.ListingEvent:com.wedding.SearchService.dto.ListingEvent"