CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS listing_db;
CREATE DATABASE IF NOT EXISTS review_db;
CREATE DATABASE IF NOT EXISTS enquiry_db;
CREATE DATABASE IF NOT EXISTS financial_db;
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';